vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        trick_images:
            uri_prefix: /images/trick
            upload_destination: '%kernel.project_dir%/public/images/trick'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
